In [15]:
%reload_ext cypher
import matplotlib
import pandas as pd
import matplotlib.pyplot
import datetime
import string
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk import ngrams
import operator
from itertools import islice
from tabulate import tabulate
pd.set_option('display.max_colwidth', -1)
import re

In [16]:
def clean_tweets(tweets):
    patternUrl = re.compile('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
    patternUsers =  re.compile('@(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
    patternTags = re.compile('#(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
    allTweets = pd.Series(tweets).str.cat(sep='\n|\n||\n')
    allTweets = patternUrl.sub('', allTweets) #removing urls 
    allTweets = patternUsers.sub('', allTweets) #removing users
    allTweets = patternTags.sub('', allTweets) #removing tags
    return allTweets

In [17]:
stop_words_ = set(stopwords.words('english'))  
new_set = set(['000', 'de', 'rt', 'http', 'https', 'amp', '1', '25', 'pm', '2', 'rtudf0a', 'udf0a', 'lifeudc68udfff', 'udfa4udc69udffb', 'udfa8', 'udf08udf37udf3audd16', 'lmaooooooooooooooooooooooooooooooooooooooooooooude02ude02', 'udf31small', '' ])
stop_words_ = stop_words_.union(new_set)

In [18]:
def getNGram(text, n, stop_words, m):
    punct_signs = list(string.punctuation)
    punct_signs.append('…')
    punct_signs.append('¿')
    for p in punct_signs:
        text = text.replace(p, ' ')
    clean_text = text.lower().split()
    clean_text = [w for w in clean_text if w not in stop_words_]
    total = len(clean_text)
    h_dict = {}   
    ngramas = ngrams(clean_text, n)
    for grams in ngramas:
        words = ' '.join(grams)        
        words = words.strip() 
        if words in h_dict:
            h_dict[words] = h_dict[words] + 1
        else: 
            h_dict[words] = 1 
    sorted_dict = sorted(h_dict.items(), key=operator.itemgetter(1), reverse=True)
    if m >=1:
        results = list(islice(sorted_dict,  m))
        results = [(v[0], v[1], v[1] * 100 / total) for v in results]
        return results
    else:
        return list(islice(sorted_dict, None))

In [19]:
ecos = [ 'BLM', 'MT', 'CCH', 'GC']
tweets_text = []

In [20]:
for eco in ecos:
    tweetsQ = %cypher match  (n:tweet)<-[r :TWEETS]-(n2:user) where n.eco = '{eco}' and n.lang = 'en' return n.tid as tid, substring(n.text, 0, 10000000) as text, n.created_at as date
    text = clean_tweets(tweetsQ.get_dataframe().text)
    tweets_text.append(text)

52663 rows affected.
363557 rows affected.
37086 rows affected.
491128 rows affected.

## Top 50 unigrams in tweets per Movement

In [21]:
for idx, eco in enumerate(ecos):
    print()
    print(eco)
    print('-----------------------------------------------------------------------')
    final = getNGram(tweets_text[idx], 1, stop_words_, 50)
    df = pd.DataFrame([x for x in final], columns = ['Ngram', 'Number', '% of the total'])
    display(df)
    print('-----------------------------------------------------------------------')

BLM
-----------------------------------------------------------------------

        Ngram  Number  % of the total
0   black      14636   2.922962
1   police     6352    1.268561
2   white      6247    1.247591
3   people     6068    1.211843
4   cops       4882    0.974986
5   follow     3905    0.779869
6   party      3333    0.665635
7   killed     2899    0.578961
8   rt♻️       2818    0.562784
9   like❤      2818    0.562784
10  outrage    2730    0.545209
11  man        2701    0.539418
12  days       2616    0.522442
13  icymi      2487    0.496680
14  four       2454    0.490089
15  larry      2415    0.482301
16  elder      2411    0.481502
17  seven      2407    0.480703
18  student    1996    0.398622
19  like       1924    0.384243
20  it’s       1872    0.373858
21  time       1851    0.369664
22  lives      1844    0.368266
23  make       1826    0.364671
24  racist     1822    0.363872
25  right      1663    0.332118
26  call       1662    0.331919
27  please     1650    0.329522
28  thing      1631    0.325728
29  us         1596    0.318738
30  think      1481    0.295771
31  say        1466    0.292775
32  matter     1400    0.279595
33  called     1387    0.276998
34  woman      1362    0.272006
35  dorm       1264    0.252434
36  women      1225    0.244645
37  2018       1225    0.244645
38  reason     1216    0.242848
39  every      1209    0.241450
40  need       1197    0.239053
41  see        1180    0.235658
42  get        1178    0.235259
43  says       1177    0.235059
44  taking     1160    0.231664
45  things     1149    0.229467
46  look       1149    0.229467
47  stop       1139    0.227470
48  nap        1115    0.222677
49  community  1099    0.219482

-----------------------------------------------------------------------

MT
-----------------------------------------------------------------------

         Ngram  Number  % of the total
0   women       52118   1.402760
1   movement    44192   1.189431
2   sexual      40897   1.100746
3   men         25717   0.692175
4   weinstein   24343   0.655194
5   people      19395   0.522018
6   like        19124   0.514724
7   harvey      18014   0.484848
8   metoo       17357   0.467165
9   know        16269   0.437881
10  one         16134   0.434248
11  rape        14500   0.390269
12  harassment  13748   0.370028
13  accused     13041   0.350999
14  don’t       12979   0.349331
15  get         12426   0.334447
16  abuse       12307   0.331244
17  woman       11958   0.321850
18  trump       11763   0.316602
19  stupid      11564   0.311246
20  raped       11251   0.302822
21  ever        11092   0.298542
22  ratified    11016   0.296496
23  want        10925   0.294047
24  assault     10594   0.285138
25  freeman     10370   0.279109
26  morgan      10304   0.277333
27  saying      10140   0.272919
28  rights      9281    0.249799
29  bill        9223    0.248238
30  latest      9116    0.245358
31  sex         8986    0.241859
32  i’m         8734    0.235076
33  support     8709    0.234403
34  think       8698    0.234107
35  new         8678    0.233569
36  era         8593    0.231281
37  would       8439    0.227136
38  it’s        8375    0.225414
39  time        8183    0.220246
40  need        7655    0.206035
41  bourdain    7474    0.201163
42  male        7406    0.199333
43  clinton     7337    0.197476
44  equal       7307    0.196668
45  many        7294    0.196319
46  see         7292    0.196265
47  might       7229    0.194569
48  feminist    7205    0.193923
49  us          7167    0.192900

-----------------------------------------------------------------------

CCH
-----------------------------------------------------------------------

            Ngram  Number  % of the total
0   climate        5117    1.406527
1   change         3197    0.878770
2   new            2533    0.696254
3   one            1946    0.534903
4   world          1583    0.435124
5   may            1403    0.385647
6   people         1367    0.375752
7   global         1302    0.357885
8   via            1302    0.357885
9   us             1295    0.355961
10  time           1184    0.325450
11  ”              1152    0.316654
12  sea            1097    0.301536
13  could          1089    0.299337
14  future         1036    0.284769
15  2018           1012    0.278172
16  today          1012    0.278172
17  need           1006    0.276523
18  stop           989     0.271850
19  ice            916     0.251784
20  carbon         843     0.231718
21  years          831     0.228420
22  energy         831     0.228420
23  california     820     0.225396
24  water          818     0.224846
25  like           817     0.224571
26  don’t          786     0.216050
27  month          783     0.215226
28  good           755     0.207529
29  help           750     0.206155
30  week           743     0.204231
31  report         740     0.203406
32  thanks         735     0.202032
33  day            726     0.199558
34  great          712     0.195710
35  last           703     0.193236
36  latest         702     0.192961
37  real           699     0.192136
38  first          699     0.192136
39  year           697     0.191587
40  make           674     0.185265
41  ocean          661     0.181691
42  environmental  658     0.180867
43  6              656     0.180317
44  take           656     0.180317
45  news           646     0.177568
46  action         641     0.176194
47  much           631     0.173445
48  fight          621     0.170696
49  daily          621     0.170696

-----------------------------------------------------------------------

GC
-----------------------------------------------------------------------

        Ngram  Number  % of the total
0   people     127702  2.251251
1   killed     117618  2.073481
2   black      112346  1.980541
3   think      104034  1.834009
4   continue   103799  1.829866
5   police     101595  1.791012
6   armed      101276  1.785388
7   gets       98684   1.739694
8   rifle      98468   1.735886
9   campus     98415   1.734952
10  they’re    98303   1.732978
11  tv         98294   1.732819
12  brings     97773   1.723634
13  pla        97703   1.722400
14  school     83776   1.476882
15  gun        62836   1.107732
16  shooting   40569   0.715188
17  guns       37025   0.652711
18  children   32511   0.573134
19  high       31327   0.552262
20  fe         30832   0.543535
21  santa      30301   0.534174
22  need       28068   0.494809
23  nra        25895   0.456501
24  15         21545   0.379815
25  ar         21475   0.378581
26  prayers    20981   0.369873
27  protect    20513   0.361622
28  mass       20268   0.357303
29  today      19843   0.349811
30  shootings  19818   0.349370
31  student    18101   0.319101
32  thoughts   17872   0.315064
33  us         17387   0.306514
34  schools    17276   0.304558
35  many       17055   0.300662
36  stop       17041   0.300415
37  laws       16512   0.291089
38  time       16430   0.289643
39  texas      15944   0.281076
40  america    15923   0.280706
41  would      15544   0.274024
42  2018       15108   0.266338
43  child      15004   0.264505
44  kids       14960   0.263729
45  year       14820   0.261261
46  state      14262   0.251424
47  death      13993   0.246682
48  shooter    13992   0.246664
49  right      13920   0.245395

-----------------------------------------------------------------------

## Top 50 bigrams in the tweets per Movement

In [22]:
for idx, actor in enumerate(ecos):
    print()
    print(actor)
    print('-----------------------------------------------------------------------')
    final = getNGram(tweets_text[idx], 2, stop_words_, 50)
    df = pd.DataFrame([x for x in final], columns = ['Ngram', 'Number', '% of the total'])
    display(df)

BLM
-----------------------------------------------------------------------

                  Ngram  Number  % of the total
0   like❤ rt♻️           2818    0.562784
1   party like❤          2818    0.562784
2   rt♻️ follow          2818    0.562784
3   black cops           2409    0.481102
4   larry elder          2408    0.480903
5   icymi larry          2406    0.480503
6   cops killed          2403    0.479904
7   four black           2389    0.477108
8   seven days           2387    0.476709
9   killed seven         2387    0.476709
10  elder four           2386    0.476509
11  days outrage         2386    0.476509
12  white people         2331    0.465525
13  black man            1826    0.364671
14  call police          1152    0.230066
15  black people         1140    0.227670
16  black student        1082    0.216087
17  nap dorm             1051    0.209896
18  it’s time            1043    0.208298
19  taking nap           1030    0.205702
20  lives matter         1028    0.205302
21  reason call          1024    0.204503
22  student taking       1024    0.204503
23  police it’s          1023    0.204304
24  dorm building        1022    0.204104
25  legitimate reason    1022    0.204104
26  building legitimate  1021    0.203904
27  witnessing black     1021    0.203904
28  right thing          894     0.178541
29  people look          882     0.176145
30  think cops           875     0.174747
31  scenario think       873     0.174347
32  cops right           873     0.174347
33  look scenario        873     0.174347
34  woman’s papers       872     0.174147
35  fact white           872     0.174147
36  thing checking       872     0.174147
37  checking woman’s     872     0.174147
38  black lives          859     0.171551
39  list things          830     0.165760
40  black list           809     0.161566
41  year old             805     0.160767
42  people color         789     0.157572
43  hello 911            681     0.136003
44  white women          674     0.134605
45  black woman          674     0.134605
46  every black          645     0.128813
47  community service    639     0.127615
48  man needs            625     0.124819
49  needs white          623     0.124420

MT
-----------------------------------------------------------------------

                     Ngram  Number  % of the total
0   harvey weinstein        16074   0.432633
1   morgan freeman          9766    0.262853
2   accused sexual          9449    0.254321
3   sexual harassment       8845    0.238064
4   sexual assault          8842    0.237983
5   people don’t            8119    0.218523
6   saying people           8042    0.216451
7   sexual misconduct       6515    0.175352
8   pride month             6282    0.169081
9   happy pride             6275    0.168892
10  anthony bourdain        5962    0.160468
11  equal rights            5962    0.160468
12  rights amendment        5797    0.156027
13  bill clinton            5496    0.147925
14  ratified equal          5487    0.147683
15  ratified era            5486    0.147656
16  illinois ratified       5484    0.147602
17  37 states               5484    0.147602
18  states ratified         5484    0.147602
19  amendment 37            5480    0.147495
20  breaking illinois       5477    0.147414
21  era mo                  5470    0.147225
22  stupid weak             5448    0.146633
23  entire premise          5372    0.144588
24  metoo movement          5372    0.144588
25  weak inconsequential    5364    0.144372
26  mazie hirono            5363    0.144346
27  senator mazie           5353    0.144076
28  whether ever            5347    0.143915
29  sexual abuse            5339    0.143700
30  know men                5338    0.143673
31  hirono asking           5337    0.143646
32  might want              5333    0.143538
33  women stupid            5333    0.143538
34  hawaii senator          5324    0.143296
35  premise women           5312    0.142973
36  men might               5302    0.142704
37  stupid know             5299    0.142623
38  inconsequential stupid  5295    0.142515
39  ever accused            4848    0.130484
40  trump nominees          4842    0.130323
41  asking trump            4841    0.130296
42  nominees whether        4841    0.130296
43  misconduct republica    4811    0.129488
44  women getting           4078    0.109760
45  like saying             4073    0.109625
46  getting raped           4056    0.109168
47  don’t support           4050    0.109006
48  okay women              4038    0.108683
49  support okay            4024    0.108306

CCH
-----------------------------------------------------------------------

                      Ngram  Number  % of the total
0   climate change           2748    0.755352
1   gain followers           503     0.138261
2   one week                 456     0.125342
3   may 11                   456     0.125342
4   week may                 456     0.125342
5   month special            454     0.124792
6   2018 6                   454     0.124792
7   end month                454     0.124792
8   6 eastern                454     0.124792
9   special extended         454     0.124792
10  deadline participate     454     0.124792
11  11 2018                  454     0.124792
12  extended one             454     0.124792
13  eastern deadline         454     0.124792
14  sea level                414     0.113798
15  people transform         382     0.105002
16  level rise               368     0.101153
17  migratory birds          357     0.098130
18  sea ice                  354     0.097305
19  survival migratory       341     0.093732
20  atlantic ocean           338     0.092907
21  acts multiplied          332     0.091258
22  multiplied billions      326     0.089609
23  billions people          326     0.089609
24  don’t care               321     0.088234
25  unlimited time           319     0.087685
26  don’t unlimited          318     0.087410
27  care grandchildren       318     0.087410
28  time ”                   317     0.087135
29  ” “do                    317     0.087135
30  “we don’t                317     0.087135
31  “do don’t                317     0.087135
32  one greatest             312     0.085760
33  stealing future          310     0.085211
34  we’ve stealing           309     0.084936
35  future ”                 309     0.084936
36  grandchildren we’ve      309     0.084936
37  global warming           308     0.084661
38  threats survival         307     0.084386
39  greatest threats         307     0.084386
40  remember one             306     0.084111
41  birds world              300     0.082462
42  need stop                294     0.080813
43  fresh water              285     0.078339
44  stop lamenting           284     0.078064
45  environmental pollution  284     0.078064
46  transform worldudf33     284     0.078064
47  set new                  282     0.077514
48  new whose                282     0.077514
49  whose underlying         282     0.077514

GC
-----------------------------------------------------------------------

               Ngram  Number  % of the total
0   black people      97972   1.727142
1   killed police     97719   1.722682
2   people continue   97704   1.722418
3   gets tv           97701   1.722365
4   rifle campus      97697   1.722294
5   think they’re     97696   1.722277
6   they’re armed     97688   1.722136
7   campus gets       97688   1.722136
8   police think      97687   1.722118
9   brings rifle      97686   1.722101
10  continue killed   97685   1.722083
11  armed brings      97684   1.722065
12  tv pla            97683   1.722048
13  santa fe          30161   0.531706
14  high school       26627   0.469406
15  school shooting   24172   0.426127
16  pla black         19418   0.342319
17  ar 15             18707   0.329785
18  thoughts prayers  16982   0.299375
19  fe high           12618   0.222442
20  tamir rice        12183   0.214773
21  school g          12125   0.213751
22  state black       12086   0.213063
23  death school      12082   0.212993
24  holding toy       12078   0.212922
25  black child       12070   0.212781
26  brought weapon    12068   0.212746
27  weapon death      12067   0.212728
28  executed holding  12065   0.212693
29  toy gun—you       12064   0.212676
30  rice executed     12064   0.212676
31  child tamir       12064   0.212676
32  gun—you brought   12064   0.212676
33  •ohio—the state   12064   0.212676
34  gun control       11132   0.196245
35  guns protect      10796   0.190322
36  mass shootings    9598    0.169203
37  gop nra           9165    0.161569
38  emma gonzalez     9004    0.158731
39  put together      8884    0.156615
40  nra put           8884    0.156615
41  moral courage     8875    0.156457
42  shown moral       8873    0.156422
43  gonzalez shown    8873    0.156422
44  courage gop       8873    0.156422
45  school student    8439    0.148771
46  student emma      8266    0.145721
47  florida high      8196    0.144487
48  together retweet  8189    0.144363
49  gun laws          7699    0.135725

# Top 50 bigrams in the tweets per Movement

In [23]:
for idx, actor in enumerate(ecos):
    print()
    print(actor)
    print('--------------------')
    final = getNGram(tweets_text[idx], 3, stop_words_, 50)
    df = pd.DataFrame([x for x in final], columns = ['Ngram', 'Number', '% of the total'])
    display(df)

BLM
--------------------

                                               Ngram  Number  % of the total
0   party like❤ rt♻️                                  2818    0.562784
1   like❤ rt♻️ follow                                 2818    0.562784
2   icymi larry elder                                 2406    0.480503
3   black cops killed                                 2398    0.478906
4   four black cops                                   2388    0.476908
5   killed seven days                                 2387    0.476709
6   larry elder four                                  2386    0.476509
7   seven days outrage                                2386    0.476509
8   cops killed seven                                 2386    0.476509
9   elder four black                                  2386    0.476509
10  student taking nap                                1024    0.204503
11  black student taking                              1023    0.204304
12  reason call police                                1022    0.204104
13  taking nap dorm                                   1022    0.204104
14  police it’s time                                  1021    0.203904
15  building legitimate reason                        1021    0.203904
16  call police it’s                                  1021    0.203904
17  nap dorm building                                 1021    0.203904
18  legitimate reason call                            1021    0.203904
19  witnessing black student                          1021    0.203904
20  dorm building legitimate                          1021    0.203904
21  white people look                                 878     0.175346
22  look scenario think                               873     0.174347
23  think cops right                                  873     0.174347
24  people look scenario                              873     0.174347
25  cops right thing                                  873     0.174347
26  scenario think cops                               873     0.174347
27  fact white people                                 872     0.174147
28  right thing checking                              872     0.174147
29  checking woman’s papers                           872     0.174147
30  thing checking woman’s                            872     0.174147
31  black list things                                 808     0.161366
32  every black man                                   623     0.124420
33  black man needs                                   622     0.124220
34  needs white women                                 621     0.124020
35  says every black                                  621     0.124020
36  lovehateplur says every                           621     0.124020
37  white women lifeudc68udfff‍udfa4udc69udffb‍udfa8  621     0.124020
38  man needs white                                   621     0.124020
39  community service black                           620     0.123820
40  performing community service                      615     0.122822
41  list things make                                  609     0.121624
42  things make suspicious                            609     0.121624
43  service black list                                609     0.121624
44  add performing community                          609     0.121624
45  make suspicious happened                          608     0.121424
46  black lives matter                                605     0.120825
47  dear white people                                 569     0.113635
48  harry noticing blm                                512     0.102252
49  noticing blm flag                                 512     0.102252

MT
--------------------

                          Ngram  Number  % of the total
0   saying people don’t          8032    0.216182
1   happy pride month            6274    0.168865
2   equal rights amendment       5796    0.156000
3   ratified equal rights        5487    0.147683
4   states ratified era          5481    0.147522
5   illinois ratified equal      5481    0.147522
6   37 states ratified           5480    0.147495
7   amendment 37 states          5480    0.147495
8   rights amendment 37          5480    0.147495
9   breaking illinois ratified   5476    0.147387
10  ratified era mo              5470    0.147225
11  stupid weak inconsequential  5354    0.144103
12  senator mazie hirono         5349    0.143969
13  mazie hirono asking          5337    0.143646
14  women stupid weak            5326    0.143350
15  hawaii senator mazie         5322    0.143242
16  entire premise women         5301    0.142677
17  men might want               5296    0.142542
18  premise women stupid         5295    0.142515
19  know men might               5295    0.142515
20  stupid know men              5295    0.142515
21  weak inconsequential stupid  5294    0.142488
22  inconsequential stupid know  5293    0.142461
23  accused sexual misconduct    4989    0.134279
24  whether ever accused         4845    0.130404
25  ever accused sexual          4845    0.130404
26  trump nominees whether       4841    0.130296
27  nominees whether ever        4841    0.130296
28  hirono asking trump          4841    0.130296
29  asking trump nominees        4841    0.130296
30  sexual misconduct republica  4811    0.129488
31  like saying people           4047    0.108925
32  people don’t support         4028    0.108414
33  don’t support okay           4024    0.108306
34  women getting raped          4019    0.108172
35  raped like saying            4016    0.108091
36  okay women getting           4016    0.108091
37  getting raped like           4015    0.108064
38  support okay women           4015    0.108064
39  people don’t suppo           4006    0.107822
40  morgan freeman latest        3995    0.107526
41  working 9 5                  3791    0.102035
42  5 summer break               3790    0.102008
43  9 5 summer                   3790    0.102008
44  y’all actually working       3789    0.101981
45  actually working 9           3789    0.101981
46  summer break metoo           3789    0.101981
47  accused sexual assault       3217    0.086586
48  male tv writers              3172    0.085375
49  sexual assault imagine       3142    0.084567

CCH
--------------------

                               Ngram  Number  % of the total
0   week may 11                       454     0.124792
1   11 2018 6                         454     0.124792
2   may 11 2018                       454     0.124792
3   6 eastern deadline                454     0.124792
4   special extended one              454     0.124792
5   extended one week                 454     0.124792
6   2018 6 eastern                    454     0.124792
7   end month special                 454     0.124792
8   one week may                      454     0.124792
9   month special extended            454     0.124792
10  eastern deadline participate      454     0.124792
11  sea level rise                    366     0.100604
12  survival migratory birds          341     0.093732
13  acts multiplied billions          326     0.089609
14  multiplied billions people        325     0.089334
15  billions people transform         322     0.088509
16  don’t care grandchildren          318     0.087410
17  don’t unlimited time              318     0.087410
18  “do don’t care                    317     0.087135
19  ” “do don’t                       317     0.087135
20  unlimited time ”                  317     0.087135
21  “we don’t unlimited               317     0.087135
22  time ” “do                        317     0.087135
23  we’ve stealing future             309     0.084936
24  care grandchildren we’ve          309     0.084936
25  grandchildren we’ve stealing      309     0.084936
26  stealing future ”                 308     0.084661
27  threats survival migratory        307     0.084386
28  one greatest threats              307     0.084386
29  remember one greatest             306     0.084111
30  greatest threats survival         306     0.084111
31  migratory birds world             300     0.082462
32  people transform worldudf33       284     0.078064
33  need stop lamenting               284     0.078064
34  value derived addressing          282     0.077514
35  whose underlying value            282     0.077514
36  derived addressing today          282     0.077514
37  environmental pollution concerns  282     0.077514
38  today environmental pollution     282     0.077514
39  addressing today environmental    282     0.077514
40  new whose underlying              282     0.077514
41  set new whose                     282     0.077514
42  underlying value derived          282     0.077514
43  climate change poses              279     0.076690
44  located himalayas potential       264     0.072567
45  glacier providing fresh           264     0.072567
46  artificial glacier providing      264     0.072567
47  fresh water village               264     0.072567
48  providing fresh water             264     0.072567
49  water village located             264     0.072567

GC
--------------------

                         Ngram  Number  % of the total
0   killed police think         97686   1.722101
1   rifle campus gets           97686   1.722101
2   campus gets tv              97686   1.722101
3   brings rifle campus         97686   1.722101
4   think they’re armed         97685   1.722083
5   police think they’re        97685   1.722083
6   armed brings rifle          97684   1.722065
7   they’re armed brings        97684   1.722065
8   people continue killed      97684   1.722065
9   continue killed police      97684   1.722065
10  black people continue       97684   1.722065
11  gets tv pla                 97683   1.722048
12  tv pla black                19417   0.342301
13  pla black people            19372   0.341508
14  santa fe high               12378   0.218211
15  state black child           12067   0.212728
16  weapon death school         12065   0.212693
17  rice executed holding       12064   0.212676
18  holding toy gun—you         12064   0.212676
19  brought weapon death        12064   0.212676
20  executed holding toy        12064   0.212676
21  •ohio—the state black       12064   0.212676
22  tamir rice executed         12064   0.212676
23  toy gun—you brought         12064   0.212676
24  black child tamir           12064   0.212676
25  child tamir rice            12064   0.212676
26  gun—you brought weapon      12064   0.212676
27  death school g              12063   0.212658
28  fe high school              11182   0.197127
29  gop nra put                 8873    0.156422
30  emma gonzalez shown         8873    0.156422
31  nra put together            8873    0.156422
32  moral courage gop           8873    0.156422
33  courage gop nra             8873    0.156422
34  shown moral courage         8873    0.156422
35  gonzalez shown moral        8873    0.156422
36  high school student         8399    0.148065
37  student emma gonzalez       8265    0.145703
38  florida high school         8196    0.144487
39  put together retweet        8189    0.144363
40  school student emma         8188    0.144346
41  pakistani exchange student  6530    0.115117
42  countries mental illness    6351    0.111961
43  illness video games         6310    0.111239
44  mental illness video        6310    0.111239
45  video games also            6305    0.111150
46  mass shootings 2018         6244    0.110075
47  also mass shootings         6228    0.109793
48  games also mass             6225    0.109740
49  innocent children murdered  6059    0.106814

## Number of Tweets per Movement

In [24]:
%cypher match (n:tweet) return n.eco as Movement, count(n)  as  Tweets

4 rows affected.

[['CCH', 40616], ['GC', 527641], ['MT', 596798], ['BLM', 60960]]

## Top 20 Hashtags per Movement - includes non-english hashtags

In [26]:
for eco in ecos:
    print(eco, '----------------------------------------------')
    df = %cypher match (n:hashtag)-[r]-() where n.eco = '{eco}' return n.hashtag as Hashtag, count(r) as degree order by degree desc limit 20
    display (df.get_dataframe())

BLM ----------------------------------------------
20 rows affected.

             Hashtag  degree
0   metoo             245944
1   guncontrol        74867
2   guncontrolnow     64838
3   blacklivesmatter  17833
4   climatechange     14646
5   timesup           10886
6   nra               8450
7   fbr               6952
8   marchforourlives  6778
9   theresistance     6589
10  trump             6061
11  neveragain        5925
12  resist            5561
13  gunreformnow      5486
14  texas             5343
15  maga              5313
16  enoughisenough    4918
17  resistance        4509
18  impeachtrump      4089
19  bluewave2018      4007

MT ----------------------------------------------
20 rows affected.

                       Hashtag  degree
0   santafe                     10013
1   harveyweinstein             4383
2   morganfreeman               3134
3   weinstein                   3117
4   미투                          3093
5   ff                          3025
6   am2dm                       2981
7   wcw                         2973
8   fbf                         2973
9   girlboss                    2536
10  feminist_shirt              2533
11  미투운동                        2143
12  schoolshooting              2016
13  mujeresaliancistasconmeade  1899
14  대학미투                        1835
15  상명대미투                       1830
16  학교2차가해                      1830
17  thoughtsandprayers          1733
18  deciudadanoaciudadanas      1597
19  withyou                     1576

CCH ----------------------------------------------
20 rows affected.

                  Hashtag  degree
0   tedcruz                650
1   sb48bonn               461
2   worldmigratorybirdday  355
3   goldenage              251
4   renewableenergy        250
5   morintoon              244
6   budget2018             231
7   renewables             225
8   kindermorgan           187
9   climatechangeisreal    169
10  sac18                  159
11  fossilfuels            152
12  talanoadialogue        149
13  climatehero            128
14  costarica              125
15  corruptgop             122
16  geoengineering         110
17  algore                 102
18  cleantech              101
19  fracking               96

GC ----------------------------------------------
20 rows affected.

                      Hashtag  degree
0   santafehighschool          10351
1   sabikasheikh               2334
2   texasshooting              1546
3   usveterans                 1032
4   veteransusa                1032
5   santafehs                  929
6   thakietees                 894
7   mt                         839
8   ifidieinaschoolshooting    717
9   universalbackgroundchecks  667
10  honorthemwithaction        595
11  shopify                    581
12  graphic_design             575
13  ammosexuals                555
14  clipping                   543
15  billboardmusicawards       387
16  gunsensenow                384
17  tedlieu                    375
18  gregabbott                 373
19  santafehigh                363